# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/Arthur/stratt/polymer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/Arthur/stratt/polymer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Arthur/stratt/polymer/CMakeFiles /Users/Arthur/stratt/polymer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Arthur/stratt/polymer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named atom_test

# Build rule for target.
atom_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 atom_test
.PHONY : atom_test

# fast build rule for target.
atom_test/fast:
	$(MAKE) -f CMakeFiles/atom_test.dir/build.make CMakeFiles/atom_test.dir/build
.PHONY : atom_test/fast

#=============================================================================
# Target rules for targets named observables_test

# Build rule for target.
observables_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 observables_test
.PHONY : observables_test

# fast build rule for target.
observables_test/fast:
	$(MAKE) -f CMakeFiles/observables_test.dir/build.make CMakeFiles/observables_test.dir/build
.PHONY : observables_test/fast

#=============================================================================
# Target rules for targets named ljpotential_test

# Build rule for target.
ljpotential_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ljpotential_test
.PHONY : ljpotential_test

# fast build rule for target.
ljpotential_test/fast:
	$(MAKE) -f CMakeFiles/ljpotential_test.dir/build.make CMakeFiles/ljpotential_test.dir/build
.PHONY : ljpotential_test/fast

#=============================================================================
# Target rules for targets named bond

# Build rule for target.
bond: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bond
.PHONY : bond

# fast build rule for target.
bond/fast:
	$(MAKE) -f CMakeFiles/bond.dir/build.make CMakeFiles/bond.dir/build
.PHONY : bond/fast

#=============================================================================
# Target rules for targets named molecule_test

# Build rule for target.
molecule_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 molecule_test
.PHONY : molecule_test

# fast build rule for target.
molecule_test/fast:
	$(MAKE) -f CMakeFiles/molecule_test.dir/build.make CMakeFiles/molecule_test.dir/build
.PHONY : molecule_test/fast

#=============================================================================
# Target rules for targets named vector_test

# Build rule for target.
vector_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vector_test
.PHONY : vector_test

# fast build rule for target.
vector_test/fast:
	$(MAKE) -f CMakeFiles/vector_test.dir/build.make CMakeFiles/vector_test.dir/build
.PHONY : vector_test/fast

#=============================================================================
# Target rules for targets named bond_test

# Build rule for target.
bond_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bond_test
.PHONY : bond_test

# fast build rule for target.
bond_test/fast:
	$(MAKE) -f CMakeFiles/bond_test.dir/build.make CMakeFiles/bond_test.dir/build
.PHONY : bond_test/fast

#=============================================================================
# Target rules for targets named vector

# Build rule for target.
vector: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vector
.PHONY : vector

# fast build rule for target.
vector/fast:
	$(MAKE) -f CMakeFiles/vector.dir/build.make CMakeFiles/vector.dir/build
.PHONY : vector/fast

#=============================================================================
# Target rules for targets named atom

# Build rule for target.
atom: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 atom
.PHONY : atom

# fast build rule for target.
atom/fast:
	$(MAKE) -f CMakeFiles/atom.dir/build.make CMakeFiles/atom.dir/build
.PHONY : atom/fast

#=============================================================================
# Target rules for targets named ljpotential

# Build rule for target.
ljpotential: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ljpotential
.PHONY : ljpotential

# fast build rule for target.
ljpotential/fast:
	$(MAKE) -f CMakeFiles/ljpotential.dir/build.make CMakeFiles/ljpotential.dir/build
.PHONY : ljpotential/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f googletest-build/googlemock/CMakeFiles/gmock.dir/build.make googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f googletest-build/googlemock/gtest/CMakeFiles/gtest_main.dir/build.make googletest-build/googlemock/gtest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f googletest-build/googlemock/gtest/CMakeFiles/gtest.dir/build.make googletest-build/googlemock/gtest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

src/atom.o: src/atom.cpp.o

.PHONY : src/atom.o

# target to build an object file
src/atom.cpp.o:
	$(MAKE) -f CMakeFiles/atom_test.dir/build.make CMakeFiles/atom_test.dir/src/atom.cpp.o
	$(MAKE) -f CMakeFiles/bond.dir/build.make CMakeFiles/bond.dir/src/atom.cpp.o
	$(MAKE) -f CMakeFiles/atom.dir/build.make CMakeFiles/atom.dir/src/atom.cpp.o
.PHONY : src/atom.cpp.o

src/atom.i: src/atom.cpp.i

.PHONY : src/atom.i

# target to preprocess a source file
src/atom.cpp.i:
	$(MAKE) -f CMakeFiles/atom_test.dir/build.make CMakeFiles/atom_test.dir/src/atom.cpp.i
	$(MAKE) -f CMakeFiles/bond.dir/build.make CMakeFiles/bond.dir/src/atom.cpp.i
	$(MAKE) -f CMakeFiles/atom.dir/build.make CMakeFiles/atom.dir/src/atom.cpp.i
.PHONY : src/atom.cpp.i

src/atom.s: src/atom.cpp.s

.PHONY : src/atom.s

# target to generate assembly for a file
src/atom.cpp.s:
	$(MAKE) -f CMakeFiles/atom_test.dir/build.make CMakeFiles/atom_test.dir/src/atom.cpp.s
	$(MAKE) -f CMakeFiles/bond.dir/build.make CMakeFiles/bond.dir/src/atom.cpp.s
	$(MAKE) -f CMakeFiles/atom.dir/build.make CMakeFiles/atom.dir/src/atom.cpp.s
.PHONY : src/atom.cpp.s

src/atom_test.o: src/atom_test.cpp.o

.PHONY : src/atom_test.o

# target to build an object file
src/atom_test.cpp.o:
	$(MAKE) -f CMakeFiles/atom_test.dir/build.make CMakeFiles/atom_test.dir/src/atom_test.cpp.o
.PHONY : src/atom_test.cpp.o

src/atom_test.i: src/atom_test.cpp.i

.PHONY : src/atom_test.i

# target to preprocess a source file
src/atom_test.cpp.i:
	$(MAKE) -f CMakeFiles/atom_test.dir/build.make CMakeFiles/atom_test.dir/src/atom_test.cpp.i
.PHONY : src/atom_test.cpp.i

src/atom_test.s: src/atom_test.cpp.s

.PHONY : src/atom_test.s

# target to generate assembly for a file
src/atom_test.cpp.s:
	$(MAKE) -f CMakeFiles/atom_test.dir/build.make CMakeFiles/atom_test.dir/src/atom_test.cpp.s
.PHONY : src/atom_test.cpp.s

src/bond.o: src/bond.cpp.o

.PHONY : src/bond.o

# target to build an object file
src/bond.cpp.o:
	$(MAKE) -f CMakeFiles/bond.dir/build.make CMakeFiles/bond.dir/src/bond.cpp.o
	$(MAKE) -f CMakeFiles/bond_test.dir/build.make CMakeFiles/bond_test.dir/src/bond.cpp.o
.PHONY : src/bond.cpp.o

src/bond.i: src/bond.cpp.i

.PHONY : src/bond.i

# target to preprocess a source file
src/bond.cpp.i:
	$(MAKE) -f CMakeFiles/bond.dir/build.make CMakeFiles/bond.dir/src/bond.cpp.i
	$(MAKE) -f CMakeFiles/bond_test.dir/build.make CMakeFiles/bond_test.dir/src/bond.cpp.i
.PHONY : src/bond.cpp.i

src/bond.s: src/bond.cpp.s

.PHONY : src/bond.s

# target to generate assembly for a file
src/bond.cpp.s:
	$(MAKE) -f CMakeFiles/bond.dir/build.make CMakeFiles/bond.dir/src/bond.cpp.s
	$(MAKE) -f CMakeFiles/bond_test.dir/build.make CMakeFiles/bond_test.dir/src/bond.cpp.s
.PHONY : src/bond.cpp.s

src/bond_test.o: src/bond_test.cpp.o

.PHONY : src/bond_test.o

# target to build an object file
src/bond_test.cpp.o:
	$(MAKE) -f CMakeFiles/bond_test.dir/build.make CMakeFiles/bond_test.dir/src/bond_test.cpp.o
.PHONY : src/bond_test.cpp.o

src/bond_test.i: src/bond_test.cpp.i

.PHONY : src/bond_test.i

# target to preprocess a source file
src/bond_test.cpp.i:
	$(MAKE) -f CMakeFiles/bond_test.dir/build.make CMakeFiles/bond_test.dir/src/bond_test.cpp.i
.PHONY : src/bond_test.cpp.i

src/bond_test.s: src/bond_test.cpp.s

.PHONY : src/bond_test.s

# target to generate assembly for a file
src/bond_test.cpp.s:
	$(MAKE) -f CMakeFiles/bond_test.dir/build.make CMakeFiles/bond_test.dir/src/bond_test.cpp.s
.PHONY : src/bond_test.cpp.s

src/ljpotential.o: src/ljpotential.cpp.o

.PHONY : src/ljpotential.o

# target to build an object file
src/ljpotential.cpp.o:
	$(MAKE) -f CMakeFiles/ljpotential_test.dir/build.make CMakeFiles/ljpotential_test.dir/src/ljpotential.cpp.o
	$(MAKE) -f CMakeFiles/ljpotential.dir/build.make CMakeFiles/ljpotential.dir/src/ljpotential.cpp.o
.PHONY : src/ljpotential.cpp.o

src/ljpotential.i: src/ljpotential.cpp.i

.PHONY : src/ljpotential.i

# target to preprocess a source file
src/ljpotential.cpp.i:
	$(MAKE) -f CMakeFiles/ljpotential_test.dir/build.make CMakeFiles/ljpotential_test.dir/src/ljpotential.cpp.i
	$(MAKE) -f CMakeFiles/ljpotential.dir/build.make CMakeFiles/ljpotential.dir/src/ljpotential.cpp.i
.PHONY : src/ljpotential.cpp.i

src/ljpotential.s: src/ljpotential.cpp.s

.PHONY : src/ljpotential.s

# target to generate assembly for a file
src/ljpotential.cpp.s:
	$(MAKE) -f CMakeFiles/ljpotential_test.dir/build.make CMakeFiles/ljpotential_test.dir/src/ljpotential.cpp.s
	$(MAKE) -f CMakeFiles/ljpotential.dir/build.make CMakeFiles/ljpotential.dir/src/ljpotential.cpp.s
.PHONY : src/ljpotential.cpp.s

src/ljpotential_test.o: src/ljpotential_test.cpp.o

.PHONY : src/ljpotential_test.o

# target to build an object file
src/ljpotential_test.cpp.o:
	$(MAKE) -f CMakeFiles/ljpotential_test.dir/build.make CMakeFiles/ljpotential_test.dir/src/ljpotential_test.cpp.o
.PHONY : src/ljpotential_test.cpp.o

src/ljpotential_test.i: src/ljpotential_test.cpp.i

.PHONY : src/ljpotential_test.i

# target to preprocess a source file
src/ljpotential_test.cpp.i:
	$(MAKE) -f CMakeFiles/ljpotential_test.dir/build.make CMakeFiles/ljpotential_test.dir/src/ljpotential_test.cpp.i
.PHONY : src/ljpotential_test.cpp.i

src/ljpotential_test.s: src/ljpotential_test.cpp.s

.PHONY : src/ljpotential_test.s

# target to generate assembly for a file
src/ljpotential_test.cpp.s:
	$(MAKE) -f CMakeFiles/ljpotential_test.dir/build.make CMakeFiles/ljpotential_test.dir/src/ljpotential_test.cpp.s
.PHONY : src/ljpotential_test.cpp.s

src/molecule.o: src/molecule.cpp.o

.PHONY : src/molecule.o

# target to build an object file
src/molecule.cpp.o:
	$(MAKE) -f CMakeFiles/molecule_test.dir/build.make CMakeFiles/molecule_test.dir/src/molecule.cpp.o
.PHONY : src/molecule.cpp.o

src/molecule.i: src/molecule.cpp.i

.PHONY : src/molecule.i

# target to preprocess a source file
src/molecule.cpp.i:
	$(MAKE) -f CMakeFiles/molecule_test.dir/build.make CMakeFiles/molecule_test.dir/src/molecule.cpp.i
.PHONY : src/molecule.cpp.i

src/molecule.s: src/molecule.cpp.s

.PHONY : src/molecule.s

# target to generate assembly for a file
src/molecule.cpp.s:
	$(MAKE) -f CMakeFiles/molecule_test.dir/build.make CMakeFiles/molecule_test.dir/src/molecule.cpp.s
.PHONY : src/molecule.cpp.s

src/molecule_test.o: src/molecule_test.cpp.o

.PHONY : src/molecule_test.o

# target to build an object file
src/molecule_test.cpp.o:
	$(MAKE) -f CMakeFiles/molecule_test.dir/build.make CMakeFiles/molecule_test.dir/src/molecule_test.cpp.o
.PHONY : src/molecule_test.cpp.o

src/molecule_test.i: src/molecule_test.cpp.i

.PHONY : src/molecule_test.i

# target to preprocess a source file
src/molecule_test.cpp.i:
	$(MAKE) -f CMakeFiles/molecule_test.dir/build.make CMakeFiles/molecule_test.dir/src/molecule_test.cpp.i
.PHONY : src/molecule_test.cpp.i

src/molecule_test.s: src/molecule_test.cpp.s

.PHONY : src/molecule_test.s

# target to generate assembly for a file
src/molecule_test.cpp.s:
	$(MAKE) -f CMakeFiles/molecule_test.dir/build.make CMakeFiles/molecule_test.dir/src/molecule_test.cpp.s
.PHONY : src/molecule_test.cpp.s

src/observables.o: src/observables.cpp.o

.PHONY : src/observables.o

# target to build an object file
src/observables.cpp.o:
	$(MAKE) -f CMakeFiles/observables_test.dir/build.make CMakeFiles/observables_test.dir/src/observables.cpp.o
.PHONY : src/observables.cpp.o

src/observables.i: src/observables.cpp.i

.PHONY : src/observables.i

# target to preprocess a source file
src/observables.cpp.i:
	$(MAKE) -f CMakeFiles/observables_test.dir/build.make CMakeFiles/observables_test.dir/src/observables.cpp.i
.PHONY : src/observables.cpp.i

src/observables.s: src/observables.cpp.s

.PHONY : src/observables.s

# target to generate assembly for a file
src/observables.cpp.s:
	$(MAKE) -f CMakeFiles/observables_test.dir/build.make CMakeFiles/observables_test.dir/src/observables.cpp.s
.PHONY : src/observables.cpp.s

src/observables_test.o: src/observables_test.cpp.o

.PHONY : src/observables_test.o

# target to build an object file
src/observables_test.cpp.o:
	$(MAKE) -f CMakeFiles/observables_test.dir/build.make CMakeFiles/observables_test.dir/src/observables_test.cpp.o
.PHONY : src/observables_test.cpp.o

src/observables_test.i: src/observables_test.cpp.i

.PHONY : src/observables_test.i

# target to preprocess a source file
src/observables_test.cpp.i:
	$(MAKE) -f CMakeFiles/observables_test.dir/build.make CMakeFiles/observables_test.dir/src/observables_test.cpp.i
.PHONY : src/observables_test.cpp.i

src/observables_test.s: src/observables_test.cpp.s

.PHONY : src/observables_test.s

# target to generate assembly for a file
src/observables_test.cpp.s:
	$(MAKE) -f CMakeFiles/observables_test.dir/build.make CMakeFiles/observables_test.dir/src/observables_test.cpp.s
.PHONY : src/observables_test.cpp.s

src/vector.o: src/vector.cpp.o

.PHONY : src/vector.o

# target to build an object file
src/vector.cpp.o:
	$(MAKE) -f CMakeFiles/bond.dir/build.make CMakeFiles/bond.dir/src/vector.cpp.o
	$(MAKE) -f CMakeFiles/vector_test.dir/build.make CMakeFiles/vector_test.dir/src/vector.cpp.o
	$(MAKE) -f CMakeFiles/vector.dir/build.make CMakeFiles/vector.dir/src/vector.cpp.o
	$(MAKE) -f CMakeFiles/atom.dir/build.make CMakeFiles/atom.dir/src/vector.cpp.o
	$(MAKE) -f CMakeFiles/ljpotential.dir/build.make CMakeFiles/ljpotential.dir/src/vector.cpp.o
.PHONY : src/vector.cpp.o

src/vector.i: src/vector.cpp.i

.PHONY : src/vector.i

# target to preprocess a source file
src/vector.cpp.i:
	$(MAKE) -f CMakeFiles/bond.dir/build.make CMakeFiles/bond.dir/src/vector.cpp.i
	$(MAKE) -f CMakeFiles/vector_test.dir/build.make CMakeFiles/vector_test.dir/src/vector.cpp.i
	$(MAKE) -f CMakeFiles/vector.dir/build.make CMakeFiles/vector.dir/src/vector.cpp.i
	$(MAKE) -f CMakeFiles/atom.dir/build.make CMakeFiles/atom.dir/src/vector.cpp.i
	$(MAKE) -f CMakeFiles/ljpotential.dir/build.make CMakeFiles/ljpotential.dir/src/vector.cpp.i
.PHONY : src/vector.cpp.i

src/vector.s: src/vector.cpp.s

.PHONY : src/vector.s

# target to generate assembly for a file
src/vector.cpp.s:
	$(MAKE) -f CMakeFiles/bond.dir/build.make CMakeFiles/bond.dir/src/vector.cpp.s
	$(MAKE) -f CMakeFiles/vector_test.dir/build.make CMakeFiles/vector_test.dir/src/vector.cpp.s
	$(MAKE) -f CMakeFiles/vector.dir/build.make CMakeFiles/vector.dir/src/vector.cpp.s
	$(MAKE) -f CMakeFiles/atom.dir/build.make CMakeFiles/atom.dir/src/vector.cpp.s
	$(MAKE) -f CMakeFiles/ljpotential.dir/build.make CMakeFiles/ljpotential.dir/src/vector.cpp.s
.PHONY : src/vector.cpp.s

src/vector_test.o: src/vector_test.cpp.o

.PHONY : src/vector_test.o

# target to build an object file
src/vector_test.cpp.o:
	$(MAKE) -f CMakeFiles/vector_test.dir/build.make CMakeFiles/vector_test.dir/src/vector_test.cpp.o
.PHONY : src/vector_test.cpp.o

src/vector_test.i: src/vector_test.cpp.i

.PHONY : src/vector_test.i

# target to preprocess a source file
src/vector_test.cpp.i:
	$(MAKE) -f CMakeFiles/vector_test.dir/build.make CMakeFiles/vector_test.dir/src/vector_test.cpp.i
.PHONY : src/vector_test.cpp.i

src/vector_test.s: src/vector_test.cpp.s

.PHONY : src/vector_test.s

# target to generate assembly for a file
src/vector_test.cpp.s:
	$(MAKE) -f CMakeFiles/vector_test.dir/build.make CMakeFiles/vector_test.dir/src/vector_test.cpp.s
.PHONY : src/vector_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... atom_test"
	@echo "... edit_cache"
	@echo "... observables_test"
	@echo "... ljpotential_test"
	@echo "... bond"
	@echo "... molecule_test"
	@echo "... vector_test"
	@echo "... bond_test"
	@echo "... vector"
	@echo "... atom"
	@echo "... rebuild_cache"
	@echo "... ljpotential"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... src/atom.o"
	@echo "... src/atom.i"
	@echo "... src/atom.s"
	@echo "... src/atom_test.o"
	@echo "... src/atom_test.i"
	@echo "... src/atom_test.s"
	@echo "... src/bond.o"
	@echo "... src/bond.i"
	@echo "... src/bond.s"
	@echo "... src/bond_test.o"
	@echo "... src/bond_test.i"
	@echo "... src/bond_test.s"
	@echo "... src/ljpotential.o"
	@echo "... src/ljpotential.i"
	@echo "... src/ljpotential.s"
	@echo "... src/ljpotential_test.o"
	@echo "... src/ljpotential_test.i"
	@echo "... src/ljpotential_test.s"
	@echo "... src/molecule.o"
	@echo "... src/molecule.i"
	@echo "... src/molecule.s"
	@echo "... src/molecule_test.o"
	@echo "... src/molecule_test.i"
	@echo "... src/molecule_test.s"
	@echo "... src/observables.o"
	@echo "... src/observables.i"
	@echo "... src/observables.s"
	@echo "... src/observables_test.o"
	@echo "... src/observables_test.i"
	@echo "... src/observables_test.s"
	@echo "... src/vector.o"
	@echo "... src/vector.i"
	@echo "... src/vector.s"
	@echo "... src/vector_test.o"
	@echo "... src/vector_test.i"
	@echo "... src/vector_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

